export const SPRINT_LIST_FETCH_TAG = 'SPRINT_LIST';
export const SPRINT_FETCH_TAG = 'SPRINT';
export const PROJECT_ACTIVITY_FETCH_TAG = 'PROJECT_ACTIVITY';
export const PROJECT_STATS_FETCH_TAG = 'PROJECT_STATS';
