export const DASHBOARD_ACTIVITIES_FETCH_TAG = 'DASHBOARD_ACTIVITIES';
export const DASHBOARD_PROJECT_TOTAL_FETCH_TAG = 'DASHBOARD_PROJECT_TOTAL';
export const DASHBOARD_TASK_ALL_FETCH_TAG = 'DASHBOARD_TASK_ALL';
export const DASHBOARD_TASK_USER_FETCH_TAG = 'DASHBOARD_TASK_USER';
